version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver   
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123#
    ports:
      - "1433:1433"
    
  identityapi:
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    container_name: identityapi
    depends_on:
      - sqlserver
    ports:
      - "5001:8080"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PostItAppDb;User=sa;Password=Password_123#;TrustServerCertificate=True;"

  postapi:
    build:
      context: .
      dockerfile: PostApi/Dockerfile
    container_name: postapi
    depends_on:
      - sqlserver
    ports:
      - "5002:8080" 
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PostItAppDb;User=sa;Password=Password_123#;TrustServerCertificate=True;"

  peopleapi:
    build:
      context: .
      dockerfile: PeopleApi/Dockerfile
    container_name: peopleapi
    depends_on:
      - sqlserver
    ports:
      - "5003:8080" 
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PostItAppDb;User=sa;Password=Password_123#;TrustServerCertificate=True;"

  blazorfrontend:
    build:
      context: .
      dockerfile: BlazorFrontend/Dockerfile
    container_name: blazorfrontend
    depends_on:
      - identityapi
      - postapi
      - peopleapi
    ports:
      - "5000:8080" 
